os:
  - linux

dist: bionic

language: c
compiler: clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make gcc-arm-none-eabi

install:

before_script:
  - arm-none-eabi-gcc --version

script: make all

cache:
  timeout: 1000
  directories:
  - downloads
  - tools
