os:
- linux
dist: bionic
language: c
compiler: arm-none-eabi-gcc
before_install:
- mkdir -p downloads tools
- if [ ! -f downloads/gcc-arm.tar.bz2 ];then wget -O downloads/gcc-arm.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2; fi
- if [ ! -e tools/gcc-arm-none-eabi-9-2020-q2-update/bin ];then tar -xjf downloads/gcc-arm.tar.bz2 -C tools; fi
- export PATH=$PATH:`pwd`/tools/gcc-arm-none-eabi-9-2020-q2-update/bin
install: 
before_script:
- arm-none-eabi-gcc --version
script: make all
cache:
  timeout: 1000
  directories:
  - downloads
  - tools
deploy:
  provider: releases
  api_key:
    secure: d5elU7mPs9AH2SeP5NgbGaZ42QOxhpUQ5yRUaNLDxdCZsKHTOzUEHknaN3TKW9M68oy0kQZDbHBy+GJB9/ixDO8iVU07E0TaUEDuoY4/I4V3NZK17CH3pVmmQqxKaGArqbNMoPH+n6jrVM2aZceT01mYvP/t23L3PZaOnx4hGYnKKB1Oyvf0bWkYyXr03yt84nBC16LmGiyxbT1tPBUMvSFX1qgQBEX/jUMm6NcgSPx9geE4k2uuhFyN14GifN0qwuJusnf3psv02o49KwPZebvUfbrWJfEEaLYhnKs3Rd4alkx6kYWepBGOWBfdl+u0BruE7ZtQoglkLVX+dBpl4/PJhjjfDOMAWTAc29rwOl0IlamhXDipQsqvH/wX1uGs4ZjVGaEIwTcP/S5GDB75W4LtuvcunmVfg3uNE1DGpDU/Ch/BpJ1yOy2O4SeKM0VoVIKOOtNMdl8QjBuLb8gBD/+hBnXtA8/EyHvBIQGIhJvK1DFcwDbY3zKJOuDwn0E8QfcP/rFxD3SRCGYGaEso/6ha6rUDl8hoayJMrfrhFKhsLiU99h6EhIAK8ak8Whgl6c3VA12XABHlcVPiJTRttiYgw9ypW2tFHzu6tWeZipcQYeDqybi4Dyyzqg3iuNROGNtgiLTvsYjCqikhEUJmud65wrAdq15hAzx83mHuLBE=
  file: "*.bin"
  file_glob: true
  on:
    tags: true
  skip_cleanup: 'true'
