os:
- linux
dist: bionic
language: c
compiler: arm-none-eabi-gcc
before_install:
- mkdir -p downloads tools
- if [ ! -f downloads/gcc-arm.tar.bz2 ];then wget -O downloads/gcc-arm.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2; fi
- if [ ! -e tools/gcc-arm-none-eabi-9-2020-q2-update/bin ];then tar -xjf downloads/gcc-arm.tar.bz2 -C tools; fi
- export PATH=$PATH:`pwd`/tools/gcc-arm-none-eabi-9-2020-q2-update/bin
install: 
before_script:
- arm-none-eabi-gcc --version
script: make all
cache:
  timeout: 1000
  directories:
  - downloads
  - tools
deploy:
  provider: releases
  api_key:
    secure: "Mr4jNFklN3UdESugVuVhZJtPSsendVLcKDHIs4yn+w2uXM5YZtp5piVykctbG78XItGlmlTkWfThFtgFa8GhHVLaDWvPldP5c8w7GetgkPy+vk/dGDY/uQoiHdqOE7P2399ERsQU0bUpTvZQRY2ZVxvv6fy9w05TctIvu8Sp12stPc5HNMjavonGT8eQxylYtg3MJuwgJ5lQX5DuPjrfmjjWvP72wPUEL8+mJnPi21cfowubBS6uP3Erb6JeWNh3WHf7nzt8ubMP6DnT+haNXmpDxHbT+9Cb0EniOfQ+rN7dbbfNPTkTTTM2GXEYXERtm3EAzw8D+R5KCz2bNb2GNWp8rH1USyLdzvVGxrNexWT/UweLu8UAWPDbwVNG8+ASHaDyRWD+Cf1uKiWg7U0SgmKlnBsnSrMgUvY+Yr49G4NVrDFUxrVh8RhUithYk7A51gkZmH+iGoTkKRh6HhnUtL8ZdQ176JuT/dMGMTJRCQgMQyjfAGT+NXQ6742f3tDeLQVSVJV2qoEEm9IuTUyLhx0b2UrLuILM2bYCzymkMf7BHicg+7WN0416qibxxdpnbnqvxU/L2016bkJM4qcHfp/pnLZtL2Slp67/215R0rwuUKG3NmknwCEC5DQBcibBJLeeJh71WNVZX1R1AKL+W/+9JogchHFQvTKXVSLszgw="
  file: "*.bin"
  file_glob: true
  on:
    tags: true
  skip_cleanup: 'true'
